### ISSUE TITLE
Put all-day events into the right timezone

### ISSUE THREAD

**Issue by nmlorg** [nmlorg/metabot#104]
Someone just added an event to their calendar for someone's birthday (on Sat, Jul 20), and it's being treated as a 24-hour event from 5 p.m. tomorrow (Fri, Jul 19) until 5 p.m. the next day because the API returns:

```yaml
items:
- created: '2024-07-18T15:44:44.000Z'
  description: ...
  end:
    date: '2024-07-21'
  eventType: default
  kind: calendar#event
  reminders:
    useDefault: false
  sequence: 0
  start:
    date: '2024-07-20'
  status: confirmed
  summary: ...
  transparency: transparent
  updated: '2024-07-18T15:44:56.837Z'
kind: calendar#events
timeZone: America/Los_Angeles
updated: '2024-07-18T15:44:56.837Z'
```

and [`m.c.google.Calendar.datetime_proto_to_local`](https://github.com/nmlorg/metabot.calendars.google/blob/0e04136108b33be18c5abe11045b139f5abadfaf/metabot/calendars/google.py#L95-L99) just passes `'2024-07-20'` through:

https://github.com/nmlorg/metabot/blob/d0110b6848e4a250921b3a5e8175ec0f9a6cfc99/metabot/util/iso8601.py#L7-L22

which correctly (if naively) gives midnight UTC on 2024-07-20 (which is 5 p.m. the day before in America/Los_Angeles).

Somewhat weirdly, non-all-day events include time zone information in both the date spec and a separate `timeZone` field:

```yaml
  end:
    dateTime: '2024-07-20T19:30:00-07:00'
    timeZone: America/Los_Angeles
  start:
    dateTime: '2024-07-20T14:30:00-07:00'
    timeZone: America/Los_Angeles
```

and `m.c.google` just relies on `m.u.iso8601` extracting the `'-07:00'` to adjust things correctly. However, while all-day events don't include any time zone information at all, `service.events().list()` still returns the calendar's default time zone, so theoretically that could be extracted and bundled in (though that would mean `m.u.iso8601` would either need to switch entirely over to using pytz, or use two entirely different approaches for doing time zone calculations).

<hr>

It is possible for a calendar to have one default time zone and a Telegram group to configure the bot to present events in a different time zone, in which case even with the above the events will still not run midnight to midnight.

Alternatively, the all-day nature of the event could be preserved all the way out to `m.u.eventutil.format_event`, but I'm leaning toward ignoring this until I see it actually happening. (All-day events in general are pretty rare in practice.)
