### ISSUE TITLE
Config/data reorganization

### ISSUE THREAD

**Issue by nmlorg** [nmlorg/metabot#18]
Right now, at the bare minimum, bot runners need to manually create a `config/` directory to store `multibot.json`. To use the [`/events` module](https://github.com/nmlorg/metabot/blob/master/metabot/modules/events.py) (via [metabot.calendars.multicalendar.MultiCalendar](https://github.com/nmlorg/metabot/blob/master/metabot/calendars/multicalendar.py)), they also need to manually create a `calendars/` directory and a `config/calendars.json` file.

- [ ] At minimum, metabot should create `config/` (and `calendars/`) for the user automatically.
- [ ] When run outside of a virtualenv, the bot should probably default to something like `~/.metabot/` or `~/.config/metabot/`. It might make sense to always use this, even inside a virtualenv. It probably makes sense to allow a directory to be the first argument (`python -m metabot ~/mybotdata`), and might further make sense to prompt for the config/data directory rather than default to `config/` or `~/.config/metabot/`.
- [ ] I chose to use JSON for the config format exclusively because a JSON module has been included in base Python since 2.6. I think it's probably fine to depend on [PyYAML](https://pypi.org/project/PyYAML/).

This might also be a good time to consolidate multibot.json and calendars.json, so:

```json
# config/multibot.json
{
    "firstbot": {
        "admins": {
            "admins": [
                12345, 
                23456
            ]
        }, 
        "moderator": {
            "-10020002000": {
                "greeting": "Another Greeting"
            }, 
            "-10010001000": {
                "greeting": "Example Greeting"
            }
        }, 
        "telegram": {
            "running": true, 
            "token": "1111:XXXX"
        }
    }, 
    "secondbot": {
        "admins": {
            "admins": [
                34567
            ]
        }, 
        "telegram": {
            "running": true, 
            "token": "2222:YYYY"
        }
    }
}

# config/calendars.json
[
    {
        "calid": "example@gmail.com",
        "name": "An Example Calendar"
    },
    {
        "calid": "other@gmail.com",
        "name": "Another Example"
    }
]
```

might look something like:

```yaml
# ~/.config/metabot/conf.yaml
bots:
  firstbot:
    admins:
      admins:
      - 12345
      - 23456
    moderator:
      -10020002000:  # Note that YAML allows keys to be numeric types!
        greeting: Another Greeting
      -10010001000:
        greeting: Example Greeting
    telegram:
      running: true
      token: 1111:XXXX
  secondbot:
    admins:
      admins:
      - 34567
    telegram:
      running: true
      token: 2222:YYYY
calendars:
  example@gmail.com:
    name: An Example Calendar
  other@gmail.com:
    name: Another Example
```

However, it might also be worth first working out an actual UI for adding new calendars, and change the format of the calendar cache files to include metadata like "title" (or even separate it entirely into per-bot configs) so the configuration process is just scanning the cache directory (`~/.config/metabot/calendars/`).
