### ISSUE TITLE
New module:  audit (logging?)

### ISSUE THREAD

**Issue by nmlorg** [nmlorg/metabot#22]
Allow bot admins to configure where audit events are logged (in addition to the metabot console). This might look something like:
```yaml
BOTNAME:
  audit:
    actions:
    - format: human friendly
      target: '@MyBotAdmin'
    - format: raw
      target: -10010001000
```
generating something like:
```
User 123456 (Adam BotAdmin, @SomeAdmin) added user 234567 to BOTNAME's admin module's admins list.
```
and:
```
[123456 @SomeAdmin 'Adam BotAdmin'] BOTNAME.admin.admins += 234567
